<?php
// Google map control sizes and locations
  // Contributed by: floridave
  // GxMagnifier image placement at bottom
// Center
$map['imageCenter'] = 'trans.gif';
$map['widthC']      = '1';
$map['heightC']     = '1';
$map['padTopC']     = '1';
$map['padLeftC']    = '1';

// Center Background
$map['imageCenterBG'] = 'trans.gif';
$map['widthCBG']      = '1';
$map['heightCBG']     = '1';
$map['padTopCBG']     = '1';
$map['padLeftCBG']    = '1';

// North
$map['imageNorth'] = 'trans.gif';
$map['widthN']     = '1';
$map['heightN']    = '1';
$map['padTopN']    = '1';
$map['padLeftN']   = '1';

// South
$map['imageSouth'] = 'trans.gif';
$map['widthS']     = '1';
$map['heightS']    = '1';
$map['padTopS']    = '1';
$map['padLeftS']   = '1';

// East
$map['imageEast'] = 'trans.gif';
$map['widthE']    = '1';
$map['heightE']   = '1';
$map['padTopE']   = '1';
$map['padLeftE']  = '1';

// West
$map['imageWest'] = 'trans.gif';
$map['widthW']    = '1';
$map['heightW']   = '1';
$map['padTopW']   = '1';
$map['padLeftW']  = '1';

// ZoomIn
$map['imageIn']   = 'zoom-in.gif';
$map['widthIn']   = '16';
$map['heightIn']  = '16';
$map['padTopIn']  = '10';
$map['padLeftIn'] = '35';

// ZoomOut
$map['imageOut']   = 'zoom-out.gif';
$map['widthOut']   = '16';
$map['heightOut']  = '16';
$map['padTopOut']  = '10';
$map['padLeftOut'] = '2';

// SlideNotch
$map['imageSlideNotch']  = 'blank.gif';
$map['widthSlideNotch']  = '0';
$map['heightSlideNotch'] = '0';

// SlideSel
$map['imageSlideSel']  = 'blank.gif';
$map['widthSlideSel']  = '0';
$map['heightSlideSel'] = '0';

// zoomControl position
$map['padTopzoomControl']  = '600';
$map['padLeftzoomControl'] = '600';

// mapTypes
$map['linkTypeColor'] = '000000';
$map['imageTypeBG']   = 'TypeBG.png';

// mapTypeMap
$map['widthTypeMap']   = '65';
$map['padTopTypeMap']  = '40';
$map['padLeftTypeMap'] = '0';

// mapTypeSat
$map['widthTypeSat']   = '65';
$map['padTopTypeSat']  = '60';
$map['padLeftTypeSat'] = '0';

// mapTypeHyb
$map['widthTypeHyb']   = '65';
$map['padTopTypeHyb']  = '80';
$map['padLeftTypeHyb'] = '0';

// GxMagnifier location
$map['GxPosY'] = '10';
$map['GxPosX'] = '20';
