<?php

$gdEnvironments[] = array(
	'name'       => '4.1.0|1.6.2-external|Linux',
	'phpVersion' => '4.1.0',
	'gdVersion'  => '1.6.2',
	'gdBundled'  => 0,
	'imageTypes' => 30,
	'constants'  => array(
		'PHP_VERSION'              => '4.1.0',
		'PHP_OS'                   => 'Linux',
		'PHP_EXTENSION_DIR'        => '/usr/share/20010901',
		'PHP_BINDIR'               => '/usr/bin',
		'PHP_LIBDIR'               => '/usr/share',
		'PHP_DATADIR'              => '/usr/share/php',
		'PHP_SYSCONFDIR'           => '/usr/share/etc',
		'PHP_LOCALSTATEDIR'        => '/usr/share/var',
		'PHP_CONFIG_FILE_PATH'     => '/etc',
		'PHP_OUTPUT_HANDLER_START' => 1,
		'PHP_OUTPUT_HANDLER_CONT'  => 2,
		'PHP_OUTPUT_HANDLER_END'   => 4,
		'IMG_GIF'                  => 1,
		'IMG_JPG'                  => 2,
		'IMG_JPEG'                 => 2,
		'IMG_PNG'                  => 4,
		'IMG_WBMP'                 => 8,
		'IMG_XPM'                  => 16,
		'IMG_COLOR_TILED'          => -5,
		'IMG_COLOR_STYLED'         => -2,
		'IMG_COLOR_BRUSHED'        => -3,
		'IMG_COLOR_STYLEDBRUSHED'  => -4,
		'IMG_COLOR_TRANSPARENT'    => -6,
	),
	'mimeTypes'  => array(
		'image/jpeg',
		'image/png',
		'image/vnd.wap.wbmp',
	),
	'phpinfo(8)' => '&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot;&gt;
&lt;html&gt;
&lt;h2 align=&quot;center&quot;&gt;&lt;a name=&quot;module_yp&quot;&gt;yp&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; cellspacing=&quot;1&quot; width=&quot;600&quot; bgcolor=&quot;#000000&quot; align=&quot;center&quot;&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;YP Support&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;enabled&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br&gt;
&lt;h2 align=&quot;center&quot;&gt;&lt;a name=&quot;module_xslt&quot;&gt;xslt&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; cellspacing=&quot;1&quot; width=&quot;600&quot; bgcolor=&quot;#000000&quot; align=&quot;center&quot;&gt;
&lt;tr valign=&quot;middle&quot; bgcolor=&quot;#9999cc&quot;&gt;&lt;th&gt;XSLT support&lt;/th&gt;&lt;th&gt;enabled&lt;/th&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br&gt;
&lt;h2 align=&quot;center&quot;&gt;&lt;a name=&quot;module_xml&quot;&gt;xml&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; cellspacing=&quot;1&quot; width=&quot;600&quot; bgcolor=&quot;#000000&quot; align=&quot;center&quot;&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;XML Support&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;active&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;XML Namespace Support&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;active&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;EXPAT Version&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;1.95.2&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br&gt;
&lt;h2 align=&quot;center&quot;&gt;&lt;a name=&quot;module_wddx&quot;&gt;wddx&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; cellspacing=&quot;1&quot; width=&quot;600&quot; bgcolor=&quot;#000000&quot; align=&quot;center&quot;&gt;
&lt;tr valign=&quot;middle&quot; bgcolor=&quot;#9999cc&quot;&gt;&lt;th&gt;WDDX Support&lt;/th&gt;&lt;th&gt;enabled&lt;/th&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;WDDX Session Serializer&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;enabled&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br&gt;
&lt;h2 align=&quot;center&quot;&gt;&lt;a name=&quot;module_swf&quot;&gt;swf&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; cellspacing=&quot;1&quot; width=&quot;600&quot; bgcolor=&quot;#000000&quot; align=&quot;center&quot;&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;swf support&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;enabled&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br&gt;
&lt;h2 align=&quot;center&quot;&gt;&lt;a name=&quot;module_standard&quot;&gt;standard&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; cellspacing=&quot;1&quot; width=&quot;600&quot; bgcolor=&quot;#000000&quot; align=&quot;center&quot;&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;Regex Library&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;Bundled library enabled&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;Dynamic Library Support&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;enabled&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;Path to sendmail&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;/usr/sbin/sendmail -t -i&amp;nbsp;&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; cellspacing=&quot;1&quot; width=&quot;600&quot; bgcolor=&quot;#000000&quot; align=&quot;center&quot;&gt;
&lt;tr valign=&quot;middle&quot; bgcolor=&quot;#9999cc&quot;&gt;&lt;th&gt;Directive&lt;/th&gt;&lt;th&gt;Local Value&lt;/th&gt;&lt;th&gt;Master Value&lt;/th&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;assert.active&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;1&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;1&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;assert.bail&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;0&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;0&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;assert.callback&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;assert.quiet_eval&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;0&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;0&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;assert.warning&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;1&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;1&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;safe_mode_allowed_env_vars&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;PHP_&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;PHP_&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;safe_mode_protected_env_vars&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;LD_LIBRARY_PATH&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;LD_LIBRARY_PATH&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;session.use_trans_sid&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;1&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;1&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;url_rewriter.tags&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;a=href,area=href,frame=src,input=src,form=fakeentry&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;a=href,area=href,frame=src,input=src,form=fakeentry&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br&gt;
&lt;h2 align=&quot;center&quot;&gt;&lt;a name=&quot;module_snmp&quot;&gt;snmp&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; cellspacing=&quot;1&quot; width=&quot;600&quot; bgcolor=&quot;#000000&quot; align=&quot;center&quot;&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;UCD-SNMP Support&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;enabled&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;UCD-SNMP Version&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;4.2.3&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br&gt;
&lt;h2 align=&quot;center&quot;&gt;&lt;a name=&quot;module_shmop&quot;&gt;shmop&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; cellspacing=&quot;1&quot; width=&quot;600&quot; bgcolor=&quot;#000000&quot; align=&quot;center&quot;&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;shmop support&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;enabled&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br&gt;
&lt;h2 align=&quot;center&quot;&gt;&lt;a name=&quot;module_session&quot;&gt;session&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; cellspacing=&quot;1&quot; width=&quot;600&quot; bgcolor=&quot;#000000&quot; align=&quot;center&quot;&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;Session Support&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;enabled&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; cellspacing=&quot;1&quot; width=&quot;600&quot; bgcolor=&quot;#000000&quot; align=&quot;center&quot;&gt;
&lt;tr valign=&quot;middle&quot; bgcolor=&quot;#9999cc&quot;&gt;&lt;th&gt;Directive&lt;/th&gt;&lt;th&gt;Local Value&lt;/th&gt;&lt;th&gt;Master Value&lt;/th&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;session.auto_start&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;Off&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;Off&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;session.cache_expire&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;180&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;180&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;session.cache_limiter&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;nocache&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;nocache&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;session.cookie_domain&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;session.cookie_lifetime&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;0&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;0&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;session.cookie_path&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;/&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;/&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;session.cookie_secure&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;Off&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;Off&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;session.entropy_file&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;session.entropy_length&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;0&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;0&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;session.gc_maxlifetime&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;1440&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;1440&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;session.gc_probability&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;1&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;1&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;session.name&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;PHPSESSID&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;PHPSESSID&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;session.referer_check&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;session.save_handler&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;files&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;files&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;session.save_path&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;/tmp&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;/tmp&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;session.serialize_handler&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;php&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;php&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;session.use_cookies&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;On&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;On&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br&gt;
&lt;h2 align=&quot;center&quot;&gt;&lt;a name=&quot;module_posix&quot;&gt;posix&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; cellspacing=&quot;1&quot; width=&quot;600&quot; bgcolor=&quot;#000000&quot; align=&quot;center&quot;&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;Revision&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;$Revision: 15342 $&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br&gt;
&lt;h2 align=&quot;center&quot;&gt;&lt;a name=&quot;module_pgsql&quot;&gt;pgsql&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; cellspacing=&quot;1&quot; width=&quot;600&quot; bgcolor=&quot;#000000&quot; align=&quot;center&quot;&gt;
&lt;tr valign=&quot;middle&quot; bgcolor=&quot;#9999cc&quot;&gt;&lt;th&gt;PostgreSQL Support&lt;/th&gt;&lt;th&gt;enabled&lt;/th&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;Active Persistent Links&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;0&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;Active Links&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;0&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; cellspacing=&quot;1&quot; width=&quot;600&quot; bgcolor=&quot;#000000&quot; align=&quot;center&quot;&gt;
&lt;tr valign=&quot;middle&quot; bgcolor=&quot;#9999cc&quot;&gt;&lt;th&gt;Directive&lt;/th&gt;&lt;th&gt;Local Value&lt;/th&gt;&lt;th&gt;Master Value&lt;/th&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;pgsql.allow_persistent&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;On&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;On&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;pgsql.max_links&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;Unlimited&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;Unlimited&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;pgsql.max_persistent&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;Unlimited&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;Unlimited&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br&gt;
&lt;h2 align=&quot;center&quot;&gt;&lt;a name=&quot;module_pcre&quot;&gt;pcre&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; cellspacing=&quot;1&quot; width=&quot;600&quot; bgcolor=&quot;#000000&quot; align=&quot;center&quot;&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;PCRE (Perl Compatible Regular Expressions) Support&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;enabled&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;PCRE Library Version&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;3.4 22-Aug-2000&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br&gt;
&lt;h2 align=&quot;center&quot;&gt;&lt;a name=&quot;module_openssl&quot;&gt;openssl&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; cellspacing=&quot;1&quot; width=&quot;600&quot; bgcolor=&quot;#000000&quot; align=&quot;center&quot;&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;OpenSSL support&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;enabled&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;OpenSSL Version&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;OpenSSL 0.9.6c [engine] 21 dec 2001&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br&gt;
&lt;h2 align=&quot;center&quot;&gt;&lt;a name=&quot;module_odbc&quot;&gt;odbc&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; cellspacing=&quot;1&quot; width=&quot;600&quot; bgcolor=&quot;#000000&quot; align=&quot;center&quot;&gt;
&lt;tr valign=&quot;middle&quot; bgcolor=&quot;#9999cc&quot;&gt;&lt;th&gt;ODBC Support&lt;/th&gt;&lt;th&gt;enabled&lt;/th&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;Active Persistent Links&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;0&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;Active Links&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;0&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;ODBC library&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;iodbc&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;ODBC_INCLUDE&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;-I/usr/local/include&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;ODBC_LFLAGS&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;-L/usr/local/lib&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;ODBC_LIBS&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;-liodbc&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; cellspacing=&quot;1&quot; width=&quot;600&quot; bgcolor=&quot;#000000&quot; align=&quot;center&quot;&gt;
&lt;tr valign=&quot;middle&quot; bgcolor=&quot;#9999cc&quot;&gt;&lt;th&gt;Directive&lt;/th&gt;&lt;th&gt;Local Value&lt;/th&gt;&lt;th&gt;Master Value&lt;/th&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;odbc.allow_persistent&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;On&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;On&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;odbc.check_persistent&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;On&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;On&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;odbc.default_db&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;odbc.default_pw&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;odbc.default_user&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;odbc.defaultbinmode&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;return as is&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;return as is&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;odbc.defaultlrl&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;return up to 4096 bytes&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;return up to 4096 bytes&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;odbc.max_links&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;Unlimited&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;Unlimited&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;odbc.max_persistent&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;Unlimited&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;Unlimited&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br&gt;
&lt;h2 align=&quot;center&quot;&gt;&lt;a name=&quot;module_mysql&quot;&gt;mysql&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; cellspacing=&quot;1&quot; width=&quot;600&quot; bgcolor=&quot;#000000&quot; align=&quot;center&quot;&gt;
&lt;tr valign=&quot;middle&quot; bgcolor=&quot;#9999cc&quot;&gt;&lt;th&gt;MySQL Support&lt;/th&gt;&lt;th&gt;enabled&lt;/th&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;Active Persistent Links&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;0&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;Active Links&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;0&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;Client API version&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;3.23.48&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;MYSQL_MODULE_TYPE&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;external&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;MYSQL_SOCKET&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;/var/lib/mysql/mysql.sock&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;MYSQL_INCLUDE&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;-I/usr/include/mysql&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;MYSQL_LIBS&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;-L/usr/lib/mysql -lmysqlclient -L/usr/lib -z&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; cellspacing=&quot;1&quot; width=&quot;600&quot; bgcolor=&quot;#000000&quot; align=&quot;center&quot;&gt;
&lt;tr valign=&quot;middle&quot; bgcolor=&quot;#9999cc&quot;&gt;&lt;th&gt;Directive&lt;/th&gt;&lt;th&gt;Local Value&lt;/th&gt;&lt;th&gt;Master Value&lt;/th&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;mysql.allow_persistent&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;On&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;On&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;mysql.default_host&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;mysql.default_password&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;mysql.default_port&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;mysql.default_socket&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;mysql.default_user&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;mysql.max_links&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;Unlimited&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;Unlimited&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;mysql.max_persistent&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;Unlimited&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;Unlimited&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br&gt;
&lt;h2 align=&quot;center&quot;&gt;&lt;a name=&quot;module_mcrypt&quot;&gt;mcrypt&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; cellspacing=&quot;1&quot; width=&quot;600&quot; bgcolor=&quot;#000000&quot; align=&quot;center&quot;&gt;
&lt;tr valign=&quot;middle&quot; bgcolor=&quot;#9999cc&quot;&gt;&lt;th&gt;mcrypt support&lt;/th&gt;&lt;th&gt;enabled&lt;/th&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;version&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;2.4.x&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;Supported ciphers&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;arcfour blowfish-compat blowfish cast-128 cast-256 des enigma gost idea loki97 mars panama rc2 rc6 rijndael-128 rijndael-192 rijndael-256 safer-sk128 safer-sk64 saferplus serpent skipjack threeway tripledes twofish wake xtea&amp;nbsp;&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;Supported modes&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;cbc cfb ecb ncfb nofb ofb stream&amp;nbsp;&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; cellspacing=&quot;1&quot; width=&quot;600&quot; bgcolor=&quot;#000000&quot; align=&quot;center&quot;&gt;
&lt;tr valign=&quot;middle&quot; bgcolor=&quot;#9999cc&quot;&gt;&lt;th&gt;Directive&lt;/th&gt;&lt;th&gt;Local Value&lt;/th&gt;&lt;th&gt;Master Value&lt;/th&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;mcrypt.algorithms_dir&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;mcrypt.modes_dir&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br&gt;
&lt;h2 align=&quot;center&quot;&gt;&lt;a name=&quot;module_mcal&quot;&gt;mcal&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; cellspacing=&quot;1&quot; width=&quot;600&quot; bgcolor=&quot;#000000&quot; align=&quot;center&quot;&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;MCAL Support&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;enabled&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;MCAL Version&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;0.6&amp;lt;BR&amp;gt;20000121&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br&gt;
&lt;h2 align=&quot;center&quot;&gt;&lt;a name=&quot;module_mbstring&quot;&gt;mbstring&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; cellspacing=&quot;1&quot; width=&quot;600&quot; bgcolor=&quot;#000000&quot; align=&quot;center&quot;&gt;
&lt;tr valign=&quot;middle&quot; bgcolor=&quot;#9999cc&quot;&gt;&lt;th&gt;Multibyte (Japanese) Support&lt;/th&gt;&lt;th&gt;enabled&lt;/th&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;http input encoding translation&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;enabled&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; cellspacing=&quot;1&quot; width=&quot;600&quot; bgcolor=&quot;#000000&quot; align=&quot;center&quot;&gt;
&lt;tr valign=&quot;middle&quot; bgcolor=&quot;#9999cc&quot;&gt;&lt;th&gt;Directive&lt;/th&gt;&lt;th&gt;Local Value&lt;/th&gt;&lt;th&gt;Master Value&lt;/th&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;mbstring.detect_order&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;mbstring.http_input&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;mbstring.http_output&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;mbstring.internal_encoding&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot;&gt;&lt;b&gt;mbstring.substitute_character&lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br&gt;
&lt;h2 align=&quot;center&quot;&gt;&lt;a name=&quot;module_ldap&quot;&gt;ldap&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; cellspacing=&quot;1&quot; width=&quot;600&quot; bgcolor=&quot;#000000&quot; align=&quot;center&quot;&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;LDAP Support&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;enabled&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;RCS Version&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;$Id: GdFunctionMatrix.inc 15342 2006-12-01 21:14:46Z andy_st $&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;Total Links&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;0/unlimited&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;API Version&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;2004&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br&gt;
&lt;h2 align=&quot;center&quot;&gt;&lt;a name=&quot;module_imap&quot;&gt;imap&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; cellspacing=&quot;1&quot; width=&quot;600&quot; bgcolor=&quot;#000000&quot; align=&quot;center&quot;&gt;
&lt;tr valign=&quot;middle&quot; bgcolor=&quot;#9999cc&quot;&gt;&lt;th&gt;IMAP Support&lt;/th&gt;&lt;th&gt;enabled&lt;/th&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;IMAP c-Client Version&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;2001&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;SSL Support&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;enabled&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br&gt;
&lt;h2 align=&quot;center&quot;&gt;&lt;a name=&quot;module_gmp&quot;&gt;gmp&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; cellspacing=&quot;1&quot; width=&quot;600&quot; bgcolor=&quot;#000000&quot; align=&quot;center&quot;&gt;
&lt;tr valign=&quot;middle&quot; bgcolor=&quot;#9999cc&quot;&gt;&lt;th&gt;gmp support&lt;/th&gt;&lt;th&gt;enabled&lt;/th&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br&gt;
&lt;h2 align=&quot;center&quot;&gt;&lt;a name=&quot;module_gettext&quot;&gt;gettext&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; cellspacing=&quot;1&quot; width=&quot;600&quot; bgcolor=&quot;#000000&quot; align=&quot;center&quot;&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;GetText Support&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;enabled&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br&gt;
&lt;h2 align=&quot;center&quot;&gt;&lt;a name=&quot;module_gd&quot;&gt;gd&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; cellspacing=&quot;1&quot; width=&quot;600&quot; bgcolor=&quot;#000000&quot; align=&quot;center&quot;&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;GD Support&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;enabled&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;GD Version&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;1.6.2 or higher&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;FreeType Support&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;enabled&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;FreeType Linkage&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;with freetype&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;T1Lib Support&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;enabled&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;JPG Support&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;enabled&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;PNG Support&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;enabled&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;WBMP Support&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;enabled&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br&gt;
&lt;h2 align=&quot;center&quot;&gt;&lt;a name=&quot;module_ftp&quot;&gt;ftp&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; cellspacing=&quot;1&quot; width=&quot;600&quot; bgcolor=&quot;#000000&quot; align=&quot;center&quot;&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;FTP support&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;enabled&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br&gt;
&lt;h2 align=&quot;center&quot;&gt;&lt;a name=&quot;module_exif&quot;&gt;exif&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; cellspacing=&quot;1&quot; width=&quot;600&quot; bgcolor=&quot;#000000&quot; align=&quot;center&quot;&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;EXIF Support&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;enabled&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br&gt;
&lt;h2 align=&quot;center&quot;&gt;&lt;a name=&quot;module_domxml&quot;&gt;domxml&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; cellspacing=&quot;1&quot; width=&quot;600&quot; bgcolor=&quot;#000000&quot; align=&quot;center&quot;&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;DOM/XML&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;enabled&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;libxml Version&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;2.4.12&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;XPath Support&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;enabled&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;XPointer Support&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;enabled&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br&gt;
&lt;h2 align=&quot;center&quot;&gt;&lt;a name=&quot;module_dba&quot;&gt;dba&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; cellspacing=&quot;1&quot; width=&quot;600&quot; bgcolor=&quot;#000000&quot; align=&quot;center&quot;&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;DBA support&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;enabled&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;Supported handlers&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;gdbm ndbm&amp;nbsp;&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br&gt;
&lt;h2 align=&quot;center&quot;&gt;&lt;a name=&quot;module_curl&quot;&gt;curl&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; cellspacing=&quot;1&quot; width=&quot;600&quot; bgcolor=&quot;#000000&quot; align=&quot;center&quot;&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;CURL support&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;enabled&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;CURL Information&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;libcurl 7.9.2 (OpenSSL 0.9.6c) (ipv6 enabled)&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br&gt;
&lt;h2 align=&quot;center&quot;&gt;&lt;a name=&quot;module_ctype&quot;&gt;ctype&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; cellspacing=&quot;1&quot; width=&quot;600&quot; bgcolor=&quot;#000000&quot; align=&quot;center&quot;&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;ctype functions&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;enabled (experimental)&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br&gt;
&lt;h2 align=&quot;center&quot;&gt;&lt;a name=&quot;module_calendar&quot;&gt;calendar&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; cellspacing=&quot;1&quot; width=&quot;600&quot; bgcolor=&quot;#000000&quot; align=&quot;center&quot;&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;Calendar support&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;enabled&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br&gt;
&lt;h2 align=&quot;center&quot;&gt;&lt;a name=&quot;module_bz2&quot;&gt;bz2&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; cellspacing=&quot;1&quot; width=&quot;600&quot; bgcolor=&quot;#000000&quot; align=&quot;center&quot;&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;BZip2 Support&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;Enabled&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;BZip2 Version&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;1.0.2, 30-Dec-2001&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br&gt;
&lt;h2 align=&quot;center&quot;&gt;&lt;a name=&quot;module_bcmath&quot;&gt;bcmath&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; cellspacing=&quot;1&quot; width=&quot;600&quot; bgcolor=&quot;#000000&quot; align=&quot;center&quot;&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;BCMath support&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;enabled&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br&gt;
&lt;h2 align=&quot;center&quot;&gt;&lt;a name=&quot;module_zlib&quot;&gt;zlib&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; cellspacing=&quot;1&quot; width=&quot;600&quot; bgcolor=&quot;#000000&quot; align=&quot;center&quot;&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;ZLib Support&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;enabled&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;\'zlib:\' fopen wrapper&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;enabled&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;Compiled Version&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;1.1.3&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;Linked Version&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;1.1.3&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br&gt;
&lt;h2 align=&quot;center&quot;&gt;&lt;a name=&quot;module_pdf&quot;&gt;pdf&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; cellspacing=&quot;1&quot; width=&quot;600&quot; bgcolor=&quot;#000000&quot; align=&quot;center&quot;&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;PDF Support&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;enabled&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;PDFlib GmbH Version&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;4.0.3&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td bgcolor=&quot;#ccccff&quot; &gt;&lt;b&gt;Revision&lt;/b&gt;&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;$Revision: 15342 $&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br&gt;
&lt;h2 align=&quot;center&quot;&gt;Additional Modules&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; cellspacing=&quot;1&quot; width=&quot;600&quot; bgcolor=&quot;#000000&quot; align=&quot;center&quot;&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td&gt;sysvshm&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td&gt;sysvsem&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td&gt;filepro&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td&gt;dbase&lt;/td&gt;&lt;/tr&gt;
&lt;tr valign=&quot;baseline&quot; bgcolor=&quot;#cccccc&quot;&gt;&lt;td&gt;session mm&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br&gt;
&lt;/body&gt;&lt;/html&gt;',
	'functions'  => array(
		'imagearc'                => true,
		'imagechar'               => true,
		'imagecharup'             => true,
		'imagecolorallocate'      => true,
		'imagepalettecopy'        => true,
		'imagecolorat'            => true,
		'imagecolorclosest'       => true,
		'imagecolorclosesthwb'    => true,
		'imagecolordeallocate'    => true,
		'imagecolorresolve'       => true,
		'imagecolorexact'         => true,
		'imagecolorset'           => true,
		'imagecolortransparent'   => true,
		'imagecolorstotal'        => true,
		'imagecolorsforindex'     => true,
		'imagecopy'               => true,
		'imagecopymerge'          => true,
		'imagecopyresized'        => true,
		'imagecreate'             => true,
		'imagecreatetruecolor'    => true,
		'imagetruecolortopalette' => true,
		'imagesetthickness'       => true,
		'imageellipse'            => true,
		'imagefilledellipse'      => true,
		'imagefilledarc'          => true,
		'imagealphablending'      => true,
		'imagecolorresolvealpha'  => true,
		'imagecolorclosestalpha'  => true,
		'imagecolorexactalpha'    => true,
		'imagecopyresampled'      => true,
		'imagesettile'            => true,
		'imagesetbrush'           => true,
		'imagesetstyle'           => true,
		'imagecopymergegray'      => true,
		'imagecreatefromstring'   => true,
		'imagecreatefrompng'      => true,
		'imagecreatefromgif'      => true,
		'imagecreatefromjpeg'     => true,
		'imagecreatefromwbmp'     => true,
		'imagecreatefromxbm'      => true,
		'imagecreatefromxpm'      => true,
		'imagecreatefromgd'       => true,
		'imagecreatefromgd2'      => true,
		'imagecreatefromgd2part'  => true,
		'imagepng'                => true,
		'imagegif'                => true,
		'imagejpeg'               => true,
		'imagewbmp'               => true,
		'imagegd'                 => true,
		'imagegd2'                => true,
		'imagedestroy'            => true,
		'imagegammacorrect'       => true,
		'imagefill'               => true,
		'imagefilledpolygon'      => true,
		'imagefilledrectangle'    => true,
		'imagefilltoborder'       => true,
		'imagefontwidth'          => true,
		'imagefontheight'         => true,
		'imageinterlace'          => true,
		'imageline'               => true,
		'imageloadfont'           => true,
		'imagepolygon'            => true,
		'imagerectangle'          => true,
		'imagesetpixel'           => true,
		'imagestring'             => true,
		'imagestringup'           => true,
		'imagesx'                 => true,
		'imagesy'                 => true,
		'imagedashedline'         => true,
		'imagettfbbox'            => true,
		'imagettftext'            => true,
		'imageftbbox'             => true,
		'imagefttext'             => true,
		'imagepsloadfont'         => true,
		'imagepsfreefont'         => true,
		'imagepsencodefont'       => true,
		'imagepsextendfont'       => true,
		'imagepsslantfont'        => true,
		'imagepstext'             => true,
		'imagepsbbox'             => true,
		'imagetypes'              => true,
		'jpeg2wbmp'               => true,
		'png2wbmp'                => true,
		'image2wbmp'              => true,
		'getimagesize'            => true,
		'iptcembed'               => true,
		'iptcparse'               => true,
	),
);
$gdEnvironments[] = array(
	'name'       => '4.3.1|2.0-bundled|Linux',
	'phpVersion' => '4.3.1',
	'gdVersion'  => '2.0',
	'gdBundled'  => 1,
	'imageTypes' => 30,
	'gd_info'    => array(
		'GD Version'         => 'bundled (2.0 compatible)',
		'FreeType Support'   => '1',
		'FreeType Linkage'   => 'with freetype',
		'T1Lib Support'      => '1',
		'GIF Read Support'   => '1',
		'GIF Create Support' => '',
		'JPG Support'        => '1',
		'PNG Support'        => '1',
		'WBMP Support'       => '1',
		'XBM Support'        => '',
	),
	'constants'  => array(
		'PHP_VERSION'              => '4.3.1',
		'PHP_OS'                   => 'Linux',
		'PHP_SAPI'                 => 'cgi',
		'PHP_EXTENSION_DIR'        => '/usr/share/extensions/no-debug-non-zts-20020429',
		'PHP_PREFIX'               => '/usr/share',
		'PHP_BINDIR'               => '/usr/bin',
		'PHP_LIBDIR'               => '/usr/share',
		'PHP_DATADIR'              => '/usr/share/php',
		'PHP_SYSCONFDIR'           => '/usr/share/etc',
		'PHP_LOCALSTATEDIR'        => '/usr/share/var',
		'PHP_CONFIG_FILE_PATH'     => '/etc',
		'PHP_CONFIG_FILE_SCAN_DIR' => '',
		'PHP_SHLIB_SUFFIX'         => 'so',
		'PHP_OUTPUT_HANDLER_START' => 1,
		'PHP_OUTPUT_HANDLER_CONT'  => 2,
		'PHP_OUTPUT_HANDLER_END'   => 4,
		'IMAGETYPE_GIF'            => 1,
		'IMAGETYPE_JPEG'           => 2,
		'IMAGETYPE_PNG'            => 3,
		'IMAGETYPE_SWF'            => 4,
		'IMAGETYPE_PSD'            => 5,
		'IMAGETYPE_BMP'            => 6,
		'IMAGETYPE_TIFF_II'        => 7,
		'IMAGETYPE_TIFF_MM'        => 8,
		'IMAGETYPE_JPC'            => 9,
		'IMAGETYPE_JP2'            => 10,
		'IMAGETYPE_JPX'            => 11,
		'IMAGETYPE_JB2'            => 12,
		'IMAGETYPE_SWC'            => 13,
		'IMAGETYPE_IFF'            => 14,
		'IMG_GIF'                  => 1,
		'IMG_JPG'                  => 2,
		'IMG_JPEG'                 => 2,
		'IMG_PNG'                  => 4,
		'IMG_WBMP'                 => 8,
		'IMG_XPM'                  => 16,
		'IMG_COLOR_TILED'          => -5,
		'IMG_COLOR_STYLED'         => -2,
		'IMG_COLOR_BRUSHED'        => -3,
		'IMG_COLOR_STYLEDBRUSHED'  => -4,
		'IMG_COLOR_TRANSPARENT'    => -6,
		'IMG_ARC_ROUNDED'          => 0,
		'IMG_ARC_PIE'              => 0,
		'IMG_ARC_CHORD'            => 1,
		'IMG_ARC_NOFILL'           => 2,
		'IMG_ARC_EDGED'            => 4,
		'IMG_EFFECT_REPLACE'       => 0,
		'IMG_EFFECT_ALPHABLEND'    => 1,
		'IMG_EFFECT_NORMAL'        => 2,
		'IMG_EFFECT_OVERLAY'       => 3,
		'GD_BUNDLED'               => 1,
	),
	'mimeTypes'  => array(
		'image/jpeg',
		'image/png',
		'image/vnd.wap.wbmp',
	),
	'phpinfo(8)' => '&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;DTD/xhtml1-transitional.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;
&lt;style type=&quot;text/css&quot;&gt;&lt;!--
body {background-color: #ffffff; color: #000000;}
body, td, th, h1, h2 {font-family: sans-serif;}
pre {margin: 0px; font-family: monospace;}
a:link {color: #000099; text-decoration: none;}
a:hover {text-decoration: underline;}
table {border-collapse: collapse;}
.center {text-align: center;}
.center table { margin-left: auto; margin-right: auto; text-align: left;}
.center th { text-align: center; !important }
td, th { border: 1px solid #000000; font-size: 75%; vertical-align: baseline;}
h1 {font-size: 150%;}
h2 {font-size: 125%;}
.p {text-align: left;}
.e {background-color: #ccccff; font-weight: bold;}
.h {background-color: #9999cc; font-weight: bold;}
.v {background-color: #cccccc;}
i {color: #666666;}
img {float: right; border: 0px;}
hr {width: 600px; align: center; background-color: #cccccc; border: 0px; height: 1px;}
//--&gt;&lt;/style&gt;
&lt;title&gt;phpinfo()&lt;/title&gt;&lt;/head&gt;
&lt;body&gt;&lt;div class=&quot;center&quot;&gt;
&lt;h2&gt;&lt;a name=&quot;module_bcmath&quot;&gt;bcmath&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;BCMath support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_bz2&quot;&gt;bz2&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;BZip2 Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;BZip2 Version &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;1.0.2, 30-Dec-2001 &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_calendar&quot;&gt;calendar&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Calendar support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_ctype&quot;&gt;ctype&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;ctype functions &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_curl&quot;&gt;curl&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;CURL support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;CURL Information &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;libcurl/7.10.2 OpenSSL/0.9.6i ipv6 zlib/1.1.4 &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_dba&quot;&gt;dba&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;DBA support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Supported handlers &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;gdbm ndbm  &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_domxml&quot;&gt;domxml&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;DOM/XML &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;DOM/XML API Version &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;20020814 &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;libxml Version &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;20503 &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;HTML Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;XPath Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;XPointer Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_exif&quot;&gt;exif&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;EXIF Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;EXIF Version &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;1.4 $Id: GdFunctionMatrix.inc 15342 2006-12-01 21:14:46Z andy_st $ &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Supported EXIF Version &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;0220 &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Supported filetypes &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;JPEG,TIFF &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_ftp&quot;&gt;ftp&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;FTP support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_gd&quot;&gt;gd&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;GD Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;GD Version &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;bundled (2.0 compatible) &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;FreeType Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;FreeType Linkage &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;with freetype &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;T1Lib Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;GIF Read Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;JPG Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;PNG Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;WBMP Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_gettext&quot;&gt;gettext&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;GetText Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_gmp&quot;&gt;gmp&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;gmp support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_iconv&quot;&gt;iconv&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;iconv support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;iconv implementation &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;glibc &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;iconv library version &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;2.3.2 &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr class=&quot;h&quot;&gt;&lt;th&gt;Directive&lt;/th&gt;&lt;th&gt;Local Value&lt;/th&gt;&lt;th&gt;Master Value&lt;/th&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;iconv.input_encoding&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;ISO-8859-1&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;ISO-8859-1&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;iconv.internal_encoding&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;ISO-8859-1&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;ISO-8859-1&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;iconv.output_encoding&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;ISO-8859-1&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;ISO-8859-1&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_imap&quot;&gt;imap&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;IMAP c-Client Version &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;2001 &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;SSL Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_ldap&quot;&gt;ldap&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;LDAP Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;RCS Version &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;$Id: GdFunctionMatrix.inc 15342 2006-12-01 21:14:46Z andy_st $ &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Total Links &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;0/unlimited &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;API Version &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;2004 &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Vendor Name &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;OpenLDAP &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Vendor Version &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;20111 &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_mbstring&quot;&gt;mbstring&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Multibyte Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Japanese support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Multibyte (japanese) regex support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr class=&quot;h&quot;&gt;&lt;th&gt;Directive&lt;/th&gt;&lt;th&gt;Local Value&lt;/th&gt;&lt;th&gt;Master Value&lt;/th&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;mbstring.detect_order&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;mbstring.encoding_translation&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Off&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Off&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;mbstring.func_overload&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;0&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;0&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;mbstring.http_input&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;pass&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;pass&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;mbstring.http_output&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;pass&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;pass&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;mbstring.internal_encoding&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;UTF-8&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;UTF-8&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;mbstring.language&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;neutral&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;neutral&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;mbstring.substitute_character&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_mcal&quot;&gt;mcal&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;MCAL Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;MCAL Version &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;0.6 - 20000121 &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_mcrypt&quot;&gt;mcrypt&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr class=&quot;h&quot;&gt;&lt;th&gt;mcrypt support&lt;/th&gt;&lt;th&gt;enabled&lt;/th&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;version &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&amp;gt;= 2.4.x &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Supported ciphers &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;idea idea mars mars rc6 rc6 skipjack skipjack cast-128 cast-128 gost gost rijndael-128 rijndael-128 twofish twofish arcfour arcfour cast-256 cast-256 loki97 loki97 rijndael-192 rijndael-192 saferplus saferplus wake wake blowfish-compat blowfish-compat des des panama panama rijndael-256 rijndael-256 serpent serpent xtea xtea blowfish blowfish enigma enigma rc2 rc2 tripledes tripledes  &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Supported modes &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;cbc cfb ctr ecb ncfb nofb ofb stream  &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr class=&quot;h&quot;&gt;&lt;th&gt;Directive&lt;/th&gt;&lt;th&gt;Local Value&lt;/th&gt;&lt;th&gt;Master Value&lt;/th&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;mcrypt.algorithms_dir&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;mcrypt.modes_dir&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_mysql&quot;&gt;mysql&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr class=&quot;h&quot;&gt;&lt;th&gt;MySQL Support&lt;/th&gt;&lt;th&gt;enabled&lt;/th&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Active Persistent Links &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;0 &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Active Links &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;0 &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Client API version &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;3.23.55 &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;MYSQL_MODULE_TYPE &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;external &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;MYSQL_SOCKET &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;/var/lib/mysql/mysql.sock &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;MYSQL_INCLUDE &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;-I/usr/include/mysql &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;MYSQL_LIBS &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;-L/usr/lib -lmysqlclient  &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr class=&quot;h&quot;&gt;&lt;th&gt;Directive&lt;/th&gt;&lt;th&gt;Local Value&lt;/th&gt;&lt;th&gt;Master Value&lt;/th&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;mysql.allow_persistent&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;On&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;On&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;mysql.connect_timeout&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;-1&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;-1&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;mysql.default_host&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;mysql.default_password&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;mysql.default_port&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;mysql.default_socket&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;mysql.default_user&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;mysql.max_links&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Unlimited&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Unlimited&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;mysql.max_persistent&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Unlimited&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Unlimited&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;mysql.trace_mode&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Off&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Off&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_odbc&quot;&gt;odbc&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr class=&quot;h&quot;&gt;&lt;th&gt;ODBC Support&lt;/th&gt;&lt;th&gt;enabled&lt;/th&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Active Persistent Links &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;0 &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Active Links &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;0 &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;ODBC library &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;iodbc &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;ODBC_INCLUDE &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;-I/usr/local/include &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;ODBC_LFLAGS &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;-L/usr/local/lib &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;ODBC_LIBS &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;-liodbc &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr class=&quot;h&quot;&gt;&lt;th&gt;Directive&lt;/th&gt;&lt;th&gt;Local Value&lt;/th&gt;&lt;th&gt;Master Value&lt;/th&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;odbc.allow_persistent&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;On&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;On&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;odbc.check_persistent&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;On&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;On&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;odbc.default_db&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;odbc.default_pw&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;odbc.default_user&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;odbc.defaultbinmode&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;return as is&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;return as is&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;odbc.defaultlrl&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;return up to 4096 bytes&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;return up to 4096 bytes&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;odbc.max_links&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Unlimited&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Unlimited&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;odbc.max_persistent&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Unlimited&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Unlimited&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_openssl&quot;&gt;openssl&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;OpenSSL support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;OpenSSL Version &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;OpenSSL 0.9.6i [engine] Feb 19 2003 &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_overload&quot;&gt;overload&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;User-Space Object Overloading Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_pcre&quot;&gt;pcre&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;PCRE (Perl Compatible Regular Expressions) Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;PCRE Library Version &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;3.92 11-Sep-2002 &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_pgsql&quot;&gt;pgsql&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr class=&quot;h&quot;&gt;&lt;th&gt;PostgreSQL Support&lt;/th&gt;&lt;th&gt;enabled&lt;/th&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;PostgreSQL(libpq) Version &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;7.3.2 &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Multibyte character support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;SSL support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Active Persistent Links &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;0 &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Active Links &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;0 &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr class=&quot;h&quot;&gt;&lt;th&gt;Directive&lt;/th&gt;&lt;th&gt;Local Value&lt;/th&gt;&lt;th&gt;Master Value&lt;/th&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;pgsql.allow_persistent&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;On&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;On&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;pgsql.auto_reset_persistent&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Off&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Off&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;pgsql.ignore_notice&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Off&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Off&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;pgsql.log_notice&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Off&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Off&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;pgsql.max_links&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Unlimited&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Unlimited&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;pgsql.max_persistent&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Unlimited&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Unlimited&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_posix&quot;&gt;posix&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Revision &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;$Revision: 15342 $ &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_qtdom&quot;&gt;qtdom&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr class=&quot;h&quot;&gt;&lt;th&gt;qtdom support&lt;/th&gt;&lt;th&gt;enabled&lt;/th&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_session&quot;&gt;session&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Session Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Registered save handlers &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;files user mm  &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr class=&quot;h&quot;&gt;&lt;th&gt;Directive&lt;/th&gt;&lt;th&gt;Local Value&lt;/th&gt;&lt;th&gt;Master Value&lt;/th&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;session.auto_start&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Off&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Off&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;session.bug_compat_42&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;On&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;On&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;session.bug_compat_warn&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;On&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;On&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;session.cache_expire&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;180&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;180&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;session.cache_limiter&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;nocache&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;nocache&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;session.cookie_domain&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;session.cookie_lifetime&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;0&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;0&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;session.cookie_path&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;/&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;/&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;session.cookie_secure&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Off&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Off&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;session.entropy_file&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;session.entropy_length&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;0&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;0&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;session.gc_dividend&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;100&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;100&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;session.gc_maxlifetime&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;1440&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;1440&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;session.gc_probability&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;1&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;1&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;session.name&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;PHPSESSID&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;PHPSESSID&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;session.referer_check&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;session.save_handler&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;files&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;files&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;session.save_path&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;/tmp&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;/tmp&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;session.serialize_handler&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;php&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;php&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;session.use_cookies&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;On&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;On&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;session.use_only_cookies&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Off&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Off&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;session.use_trans_sid&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Off&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Off&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_shmop&quot;&gt;shmop&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;shmop support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_snmp&quot;&gt;snmp&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;UCD-SNMP Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;UCD-SNMP Version &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;4.2.6 &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_standard&quot;&gt;standard&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Regex Library &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Bundled library enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Dynamic Library Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Path to sendmail &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;/usr/sbin/sendmail -t -i  &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr class=&quot;h&quot;&gt;&lt;th&gt;Directive&lt;/th&gt;&lt;th&gt;Local Value&lt;/th&gt;&lt;th&gt;Master Value&lt;/th&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;assert.active&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;1&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;1&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;assert.bail&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;0&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;0&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;assert.callback&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;assert.quiet_eval&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;0&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;0&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;assert.warning&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;1&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;1&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;auto_detect_line_endings&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;0&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;0&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;default_socket_timeout&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;60&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;60&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;safe_mode_allowed_env_vars&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;PHP_&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;PHP_&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;safe_mode_protected_env_vars&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;LD_LIBRARY_PATH&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;LD_LIBRARY_PATH&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;url_rewriter.tags&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;a=href,area=href,frame=src,input=src,form=,fieldset=&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;a=href,area=href,frame=src,input=src,form=,fieldset=&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;user_agent&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_tokenizer&quot;&gt;tokenizer&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Tokenizer Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_wddx&quot;&gt;wddx&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr class=&quot;h&quot;&gt;&lt;th&gt;WDDX Support&lt;/th&gt;&lt;th&gt;enabled&lt;/th&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;WDDX Session Serializer &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_xml&quot;&gt;xml&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;XML Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;active &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;XML Namespace Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;active &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;EXPAT Version &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;1.95.2 &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_xslt&quot;&gt;xslt&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;XSLT support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Backend &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Sablotron &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Sablotron Version &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;0.96 &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_yp&quot;&gt;yp&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;YP Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_zlib&quot;&gt;zlib&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;ZLib Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Compiled Version &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;1.1.4 &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Linked Version &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;1.1.4 &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr class=&quot;h&quot;&gt;&lt;th&gt;Directive&lt;/th&gt;&lt;th&gt;Local Value&lt;/th&gt;&lt;th&gt;Master Value&lt;/th&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;zlib.output_compression&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Off&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Off&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;zlib.output_compression_level&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;-1&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;-1&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;zlib.output_handler&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;Additional Modules&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr class=&quot;h&quot;&gt;&lt;th&gt;Module Name&lt;/th&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td&gt;dbase&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td&gt;filepro&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td&gt;readline&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td&gt;sysvsem&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td&gt;sysvshm&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;/div&gt;&lt;/body&gt;&lt;/html&gt;',
	'functions'  => array(
		'gd_info'                 => true,
		'imagearc'                => true,
		'imageellipse'            => true,
		'imagechar'               => true,
		'imagecharup'             => true,
		'imagecolorallocate'      => true,
		'imagepalettecopy'        => true,
		'imagecreatefromstring'   => true,
		'imagecolorat'            => true,
		'imagecolorclosest'       => true,
		'imagecolorclosesthwb'    => true,
		'imagecolordeallocate'    => true,
		'imagecolorresolve'       => true,
		'imagecolorexact'         => true,
		'imagecolorset'           => true,
		'imagecolortransparent'   => true,
		'imagecolorstotal'        => true,
		'imagecolorsforindex'     => true,
		'imagecopy'               => true,
		'imagecopymerge'          => true,
		'imagecopymergegray'      => true,
		'imagecopyresized'        => true,
		'imagecreate'             => true,
		'imagecreatetruecolor'    => true,
		'imagetruecolortopalette' => true,
		'imagesetthickness'       => true,
		'imagefilledarc'          => true,
		'imagefilledellipse'      => true,
		'imagealphablending'      => true,
		'imagecolorresolvealpha'  => true,
		'imagecolorclosestalpha'  => true,
		'imagecolorexactalpha'    => true,
		'imagecopyresampled'      => true,
		'imagerotate'             => true,
		'imagesettile'            => true,
		'imagesetbrush'           => true,
		'imagesetstyle'           => true,
		'imagecreatefrompng'      => true,
		'imagecreatefromgif'      => true,
		'imagecreatefromjpeg'     => true,
		'imagecreatefromwbmp'     => true,
		'imagecreatefromxpm'      => true,
		'imagecreatefromgd'       => true,
		'imagecreatefromgd2'      => true,
		'imagecreatefromgd2part'  => true,
		'imagepng'                => true,
		'imagejpeg'               => true,
		'imagewbmp'               => true,
		'imagegd'                 => true,
		'imagegd2'                => true,
		'imagedestroy'            => true,
		'imagegammacorrect'       => true,
		'imagefill'               => true,
		'imagefilledpolygon'      => true,
		'imagefilledrectangle'    => true,
		'imagefilltoborder'       => true,
		'imagefontwidth'          => true,
		'imagefontheight'         => true,
		'imageinterlace'          => true,
		'imageline'               => true,
		'imageloadfont'           => true,
		'imagepolygon'            => true,
		'imagerectangle'          => true,
		'imagesetpixel'           => true,
		'imagestring'             => true,
		'imagestringup'           => true,
		'imagesx'                 => true,
		'imagesy'                 => true,
		'imagedashedline'         => true,
		'imagettfbbox'            => true,
		'imagettftext'            => true,
		'imageftbbox'             => true,
		'imagefttext'             => true,
		'imagepsloadfont'         => true,
		'imagepsfreefont'         => true,
		'imagepsencodefont'       => true,
		'imagepsextendfont'       => true,
		'imagepsslantfont'        => true,
		'imagepstext'             => true,
		'imagepsbbox'             => true,
		'imagetypes'              => true,
		'jpeg2wbmp'               => true,
		'png2wbmp'                => true,
		'image2wbmp'              => true,
		'imagelayereffect'        => true,
		'imagecolormatch'         => true,
		'getimagesize'            => true,
		'image_type_to_mime_type' => true,
		'iptcembed'               => true,
		'iptcparse'               => true,
	),
);
$gdEnvironments[] = array(
	'name'       => '4.3.9RC1|2.0.28-bundled|Linux',
	'phpVersion' => '4.3.9RC1',
	'gdVersion'  => '2.0.28',
	'gdBundled'  => 1,
	'imageTypes' => 31,
	'gd_info'    => array(
		'GD Version'                       => 'bundled (2.0.28 compatible)',
		'FreeType Support'                 => '1',
		'FreeType Linkage'                 => 'with freetype',
		'T1Lib Support'                    => '1',
		'GIF Read Support'                 => '1',
		'GIF Create Support'               => '1',
		'JPG Support'                      => '1',
		'PNG Support'                      => '1',
		'WBMP Support'                     => '1',
		'XBM Support'                      => '1',
		'JIS-mapped Japanese Font Support' => '',
	),
	'constants'  => array(
		'PHP_VERSION'              => '4.3.9RC1',
		'PHP_OS'                   => 'Linux',
		'PHP_SAPI'                 => 'cgi',
		'PHP_EXTENSION_DIR'        => '/usr/share/extensions/no-debug-non-zts-20020429',
		'PHP_PREFIX'               => '/usr/share',
		'PHP_BINDIR'               => '/usr/bin',
		'PHP_LIBDIR'               => '/usr/share',
		'PHP_DATADIR'              => '/usr/share/php',
		'PHP_SYSCONFDIR'           => '/usr/share/etc',
		'PHP_LOCALSTATEDIR'        => '/usr/share/var',
		'PHP_CONFIG_FILE_PATH'     => '/etc',
		'PHP_CONFIG_FILE_SCAN_DIR' => '',
		'PHP_SHLIB_SUFFIX'         => 'so',
		'PHP_OUTPUT_HANDLER_START' => 1,
		'PHP_OUTPUT_HANDLER_CONT'  => 2,
		'PHP_OUTPUT_HANDLER_END'   => 4,
		'IMAGETYPE_GIF'            => 1,
		'IMAGETYPE_JPEG'           => 2,
		'IMAGETYPE_PNG'            => 3,
		'IMAGETYPE_SWF'            => 4,
		'IMAGETYPE_PSD'            => 5,
		'IMAGETYPE_BMP'            => 6,
		'IMAGETYPE_TIFF_II'        => 7,
		'IMAGETYPE_TIFF_MM'        => 8,
		'IMAGETYPE_JPC'            => 9,
		'IMAGETYPE_JP2'            => 10,
		'IMAGETYPE_JPX'            => 11,
		'IMAGETYPE_JB2'            => 12,
		'IMAGETYPE_SWC'            => 13,
		'IMAGETYPE_IFF'            => 14,
		'IMAGETYPE_WBMP'           => 15,
		'IMAGETYPE_JPEG2000'       => 9,
		'IMAGETYPE_XBM'            => 16,
		'IMG_GIF'                  => 1,
		'IMG_JPG'                  => 2,
		'IMG_JPEG'                 => 2,
		'IMG_PNG'                  => 4,
		'IMG_WBMP'                 => 8,
		'IMG_XPM'                  => 16,
		'IMG_COLOR_TILED'          => -5,
		'IMG_COLOR_STYLED'         => -2,
		'IMG_COLOR_BRUSHED'        => -3,
		'IMG_COLOR_STYLEDBRUSHED'  => -4,
		'IMG_COLOR_TRANSPARENT'    => -6,
		'IMG_ARC_ROUNDED'          => 0,
		'IMG_ARC_PIE'              => 0,
		'IMG_ARC_CHORD'            => 1,
		'IMG_ARC_NOFILL'           => 2,
		'IMG_ARC_EDGED'            => 4,
		'IMG_GD2_RAW'              => 1,
		'IMG_GD2_COMPRESSED'       => 2,
		'IMG_EFFECT_REPLACE'       => 0,
		'IMG_EFFECT_ALPHABLEND'    => 1,
		'IMG_EFFECT_NORMAL'        => 2,
		'IMG_EFFECT_OVERLAY'       => 3,
		'GD_BUNDLED'               => 1,
	),
	'mimeTypes'  => array(
		'image/gif',
		'image/jpeg',
		'image/png',
		'image/vnd.wap.wbmp',
	),
	'phpinfo(8)' => '&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;DTD/xhtml1-transitional.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;
&lt;style type=&quot;text/css&quot;&gt;&lt;!--
body {background-color: #ffffff; color: #000000;}
body, td, th, h1, h2 {font-family: sans-serif;}
pre {margin: 0px; font-family: monospace;}
a:link {color: #000099; text-decoration: none; background-color: #ffffff;}
a:hover {text-decoration: underline;}
table {border-collapse: collapse;}
.center {text-align: center;}
.center table { margin-left: auto; margin-right: auto; text-align: left;}
.center th { text-align: center !important; }
td, th { border: 1px solid #000000; font-size: 75%; vertical-align: baseline;}
h1 {font-size: 150%;}
h2 {font-size: 125%;}
.p {text-align: left;}
.e {background-color: #ccccff; font-weight: bold; color: #000000;}
.h {background-color: #9999cc; font-weight: bold; color: #000000;}
.v {background-color: #cccccc; color: #000000;}
i {color: #666666; background-color: #cccccc;}
img {float: right; border: 0px;}
hr {width: 600px; background-color: #cccccc; border: 0px; height: 1px; color: #000000;}
//--&gt;&lt;/style&gt;
&lt;title&gt;phpinfo()&lt;/title&gt;&lt;/head&gt;
&lt;body&gt;&lt;div class=&quot;center&quot;&gt;
&lt;h2&gt;&lt;a name=&quot;module_bcmath&quot;&gt;bcmath&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;BCMath support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_bz2&quot;&gt;bz2&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;BZip2 Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;BZip2 Version &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;1.0.2, 30-Dec-2001 &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_calendar&quot;&gt;calendar&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Calendar support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_ctype&quot;&gt;ctype&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;ctype functions &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_curl&quot;&gt;curl&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;CURL support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;CURL Information &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;libcurl/7.12.1 OpenSSL/0.9.6c zlib/1.1.3 &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_dba&quot;&gt;dba&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;DBA support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Supported handlers &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;gdbm ndbm cdb cdb_make inifile flatfile  &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_domxml&quot;&gt;domxml&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;DOM/XML &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;DOM/XML API Version &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;20020815 &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;libxml Version &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;20430 &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;HTML Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;XPath Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;XPointer Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_exif&quot;&gt;exif&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;EXIF Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;EXIF Version &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;1.4 $Id: GdFunctionMatrix.inc 15342 2006-12-01 21:14:46Z andy_st $ &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Supported EXIF Version &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;0220 &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Supported filetypes &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;JPEG,TIFF &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_ftp&quot;&gt;ftp&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;FTP support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_gd&quot;&gt;gd&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;GD Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;GD Version &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;bundled (2.0.28 compatible) &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;FreeType Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;FreeType Linkage &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;with freetype &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;T1Lib Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;GIF Read Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;GIF Create Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;JPG Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;PNG Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;WBMP Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;XBM Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_gettext&quot;&gt;gettext&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;GetText Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_gmp&quot;&gt;gmp&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;gmp support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_imap&quot;&gt;imap&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;IMAP c-Client Version &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;2001 &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;SSL Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_ldap&quot;&gt;ldap&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;LDAP Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;RCS Version &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;$Id: GdFunctionMatrix.inc 15342 2006-12-01 21:14:46Z andy_st $ &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Total Links &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;0/unlimited &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;API Version &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;2004 &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Vendor Name &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;OpenLDAP &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Vendor Version &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;20023 &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_mbstring&quot;&gt;mbstring&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Multibyte Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Japanese support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Simplified chinese support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Traditional chinese support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Korean support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Russian support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Multibyte (japanese) regex support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr class=&quot;h&quot;&gt;&lt;th colspan=&quot;2&quot;&gt;mbstring extension makes use of &quot;streamable kanji code filter and converter&quot;, which is distributed under the GNU Lesser General Public License version 2.1.&lt;/th&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr class=&quot;h&quot;&gt;&lt;th&gt;Directive&lt;/th&gt;&lt;th&gt;Local Value&lt;/th&gt;&lt;th&gt;Master Value&lt;/th&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;mbstring.detect_order&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;mbstring.encoding_translation&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Off&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Off&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;mbstring.func_overload&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;0&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;0&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;mbstring.http_input&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;pass&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;pass&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;mbstring.http_output&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;pass&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;pass&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;mbstring.internal_encoding&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;ISO-8859-1&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;mbstring.language&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;neutral&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;neutral&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;mbstring.substitute_character&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_mcal&quot;&gt;mcal&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;MCAL Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;MCAL Version &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;0.6 - 20000121 &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_mcrypt&quot;&gt;mcrypt&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr class=&quot;h&quot;&gt;&lt;th&gt;mcrypt support&lt;/th&gt;&lt;th&gt;enabled&lt;/th&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;version &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&amp;gt;= 2.4.x &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Supported ciphers &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;arcfour blowfish-compat blowfish cast-128 cast-256 des enigma gost idea loki97 mars panama rc2 rc6 rijndael-128 rijndael-192 rijndael-256 safer-sk128 safer-sk64 saferplus serpent skipjack threeway tripledes twofish wake xtea  &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Supported modes &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;cbc cfb ecb ncfb nofb ofb stream  &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr class=&quot;h&quot;&gt;&lt;th&gt;Directive&lt;/th&gt;&lt;th&gt;Local Value&lt;/th&gt;&lt;th&gt;Master Value&lt;/th&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;mcrypt.algorithms_dir&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;mcrypt.modes_dir&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_mysql&quot;&gt;mysql&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr class=&quot;h&quot;&gt;&lt;th&gt;MySQL Support&lt;/th&gt;&lt;th&gt;enabled&lt;/th&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Active Persistent Links &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;0 &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Active Links &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;0 &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Client API version &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;3.23.53 &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;MYSQL_MODULE_TYPE &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;external &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;MYSQL_SOCKET &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;/var/lib/mysql/mysql.sock &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;MYSQL_INCLUDE &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;-I/usr/include/mysql &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;MYSQL_LIBS &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;-L/usr/lib -lmysqlclient  &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr class=&quot;h&quot;&gt;&lt;th&gt;Directive&lt;/th&gt;&lt;th&gt;Local Value&lt;/th&gt;&lt;th&gt;Master Value&lt;/th&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;mysql.allow_persistent&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;On&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;On&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;mysql.connect_timeout&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;60&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;60&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;mysql.default_host&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;mysql.default_password&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;mysql.default_port&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;mysql.default_socket&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;mysql.default_user&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;mysql.max_links&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Unlimited&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Unlimited&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;mysql.max_persistent&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Unlimited&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Unlimited&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;mysql.trace_mode&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Off&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Off&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_odbc&quot;&gt;odbc&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr class=&quot;h&quot;&gt;&lt;th&gt;ODBC Support&lt;/th&gt;&lt;th&gt;enabled&lt;/th&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Active Persistent Links &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;0 &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Active Links &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;0 &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;ODBC library &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;iodbc &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;ODBC_INCLUDE &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;-I/usr/local/include &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;ODBC_LFLAGS &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;-L/usr/local/lib &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;ODBC_LIBS &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;-liodbc &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr class=&quot;h&quot;&gt;&lt;th&gt;Directive&lt;/th&gt;&lt;th&gt;Local Value&lt;/th&gt;&lt;th&gt;Master Value&lt;/th&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;odbc.allow_persistent&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;On&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;On&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;odbc.check_persistent&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;On&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;On&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;odbc.default_db&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;odbc.default_pw&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;odbc.default_user&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;odbc.defaultbinmode&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;return as is&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;return as is&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;odbc.defaultlrl&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;return up to 4096 bytes&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;return up to 4096 bytes&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;odbc.max_links&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Unlimited&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Unlimited&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;odbc.max_persistent&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Unlimited&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Unlimited&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_openssl&quot;&gt;openssl&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;OpenSSL support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;OpenSSL Version &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;OpenSSL 0.9.6c [engine] 21 dec 2001 &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_overload&quot;&gt;overload&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;User-Space Object Overloading Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_pcre&quot;&gt;pcre&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;PCRE (Perl Compatible Regular Expressions) Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;PCRE Library Version &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;4.5 01-December-2003 &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_pgsql&quot;&gt;pgsql&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr class=&quot;h&quot;&gt;&lt;th&gt;PostgreSQL Support&lt;/th&gt;&lt;th&gt;enabled&lt;/th&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;PostgreSQL(libpq) Version &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;7.2 &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Multibyte character support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;SSL support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Active Persistent Links &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;0 &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Active Links &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;0 &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr class=&quot;h&quot;&gt;&lt;th&gt;Directive&lt;/th&gt;&lt;th&gt;Local Value&lt;/th&gt;&lt;th&gt;Master Value&lt;/th&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;pgsql.allow_persistent&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;On&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;On&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;pgsql.auto_reset_persistent&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Off&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Off&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;pgsql.ignore_notice&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Off&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Off&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;pgsql.log_notice&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Off&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Off&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;pgsql.max_links&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Unlimited&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Unlimited&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;pgsql.max_persistent&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Unlimited&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Unlimited&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_posix&quot;&gt;posix&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Revision &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;$Revision: 15342 $ &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_qtdom&quot;&gt;qtdom&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr class=&quot;h&quot;&gt;&lt;th&gt;qtdom support&lt;/th&gt;&lt;th&gt;enabled&lt;/th&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_session&quot;&gt;session&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Session Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Registered save handlers &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;files user mm  &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr class=&quot;h&quot;&gt;&lt;th&gt;Directive&lt;/th&gt;&lt;th&gt;Local Value&lt;/th&gt;&lt;th&gt;Master Value&lt;/th&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;session.auto_start&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Off&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Off&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;session.bug_compat_42&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;On&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;On&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;session.bug_compat_warn&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;On&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;On&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;session.cache_expire&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;180&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;180&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;session.cache_limiter&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;nocache&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;nocache&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;session.cookie_domain&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;session.cookie_lifetime&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;0&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;0&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;session.cookie_path&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;/&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;/&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;session.cookie_secure&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Off&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Off&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;session.entropy_file&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;session.entropy_length&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;0&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;0&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;session.gc_divisor&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;100&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;100&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;session.gc_maxlifetime&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;1440&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;1440&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;session.gc_probability&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;1&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;1&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;session.name&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;PHPSESSID&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;PHPSESSID&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;session.referer_check&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;session.save_handler&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;files&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;files&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;session.save_path&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;/tmp&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;/tmp&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;session.serialize_handler&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;php&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;php&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;session.use_cookies&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;On&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;On&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;session.use_only_cookies&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Off&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Off&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;session.use_trans_sid&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Off&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Off&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_shmop&quot;&gt;shmop&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;shmop support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_snmp&quot;&gt;snmp&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;UCD-SNMP Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;UCD-SNMP Version &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;4.2.3 &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_standard&quot;&gt;standard&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Regex Library &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Bundled library enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Dynamic Library Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Path to sendmail &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;/usr/sbin/sendmail -t -i  &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr class=&quot;h&quot;&gt;&lt;th&gt;Directive&lt;/th&gt;&lt;th&gt;Local Value&lt;/th&gt;&lt;th&gt;Master Value&lt;/th&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;assert.active&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;1&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;1&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;assert.bail&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;0&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;0&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;assert.callback&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;assert.quiet_eval&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;0&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;0&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;assert.warning&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;1&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;1&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;auto_detect_line_endings&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;0&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;0&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;default_socket_timeout&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;60&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;60&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;safe_mode_allowed_env_vars&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;PHP_&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;PHP_&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;safe_mode_protected_env_vars&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;LD_LIBRARY_PATH&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;LD_LIBRARY_PATH&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;url_rewriter.tags&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;a=href,area=href,frame=src,input=src,form=,fieldset=&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;a=href,area=href,frame=src,input=src,form=,fieldset=&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;user_agent&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_swf&quot;&gt;swf&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;swf support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_tokenizer&quot;&gt;tokenizer&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Tokenizer Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_wddx&quot;&gt;wddx&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr class=&quot;h&quot;&gt;&lt;th&gt;WDDX Support&lt;/th&gt;&lt;th&gt;enabled&lt;/th&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;WDDX Session Serializer &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_xml&quot;&gt;xml&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;XML Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;active &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;XML Namespace Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;active &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;EXPAT Version &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;1.95.6 &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_xslt&quot;&gt;xslt&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;XSLT support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Backend &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Sablotron &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Sablotron Version &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;0.96 &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_yp&quot;&gt;yp&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;YP Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;&lt;a name=&quot;module_zlib&quot;&gt;zlib&lt;/a&gt;&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;ZLib Support &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;enabled &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Compiled Version &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;1.1.3 &lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;Linked Version &lt;/td&gt;&lt;td class=&quot;v&quot;&gt;1.1.3 &lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr class=&quot;h&quot;&gt;&lt;th&gt;Directive&lt;/th&gt;&lt;th&gt;Local Value&lt;/th&gt;&lt;th&gt;Master Value&lt;/th&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;zlib.output_compression&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Off&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;Off&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;zlib.output_compression_level&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;-1&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;-1&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td class=&quot;e&quot;&gt;zlib.output_handler&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;td class=&quot;v&quot;&gt;&lt;i&gt;no value&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;h2&gt;Additional Modules&lt;/h2&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;3&quot; width=&quot;600&quot;&gt;
&lt;tr class=&quot;h&quot;&gt;&lt;th&gt;Module Name&lt;/th&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td&gt;dbase&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td&gt;filepro&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td&gt;sysvsem&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td&gt;sysvshm&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;&lt;br /&gt;
&lt;/div&gt;&lt;/body&gt;&lt;/html&gt;',
	'functions'  => array(
		'gd_info'                 => true,
		'imagearc'                => true,
		'imageellipse'            => true,
		'imagechar'               => true,
		'imagecharup'             => true,
		'imagecolorat'            => true,
		'imagecolorallocate'      => true,
		'imagepalettecopy'        => true,
		'imagecreatefromstring'   => true,
		'imagecolorclosest'       => true,
		'imagecolorclosesthwb'    => true,
		'imagecolordeallocate'    => true,
		'imagecolorresolve'       => true,
		'imagecolorexact'         => true,
		'imagecolorset'           => true,
		'imagecolortransparent'   => true,
		'imagecolorstotal'        => true,
		'imagecolorsforindex'     => true,
		'imagecopy'               => true,
		'imagecopymerge'          => true,
		'imagecopymergegray'      => true,
		'imagecopyresized'        => true,
		'imagecreate'             => true,
		'imagecreatetruecolor'    => true,
		'imageistruecolor'        => true,
		'imagetruecolortopalette' => true,
		'imagesetthickness'       => true,
		'imagefilledarc'          => true,
		'imagefilledellipse'      => true,
		'imagealphablending'      => true,
		'imagesavealpha'          => true,
		'imagecolorallocatealpha' => true,
		'imagecolorresolvealpha'  => true,
		'imagecolorclosestalpha'  => true,
		'imagecolorexactalpha'    => true,
		'imagecopyresampled'      => true,
		'imagerotate'             => true,
		'imageantialias'          => true,
		'imagesettile'            => true,
		'imagesetbrush'           => true,
		'imagesetstyle'           => true,
		'imagecreatefrompng'      => true,
		'imagecreatefromgif'      => true,
		'imagecreatefromjpeg'     => true,
		'imagecreatefromwbmp'     => true,
		'imagecreatefromxbm'      => true,
		'imagecreatefromxpm'      => true,
		'imagecreatefromgd'       => true,
		'imagecreatefromgd2'      => true,
		'imagecreatefromgd2part'  => true,
		'imagepng'                => true,
		'imagegif'                => true,
		'imagejpeg'               => true,
		'imagewbmp'               => true,
		'imagegd'                 => true,
		'imagegd2'                => true,
		'imagedestroy'            => true,
		'imagegammacorrect'       => true,
		'imagefill'               => true,
		'imagefilledpolygon'      => true,
		'imagefilledrectangle'    => true,
		'imagefilltoborder'       => true,
		'imagefontwidth'          => true,
		'imagefontheight'         => true,
		'imageinterlace'          => true,
		'imageline'               => true,
		'imageloadfont'           => true,
		'imagepolygon'            => true,
		'imagerectangle'          => true,
		'imagesetpixel'           => true,
		'imagestring'             => true,
		'imagestringup'           => true,
		'imagesx'                 => true,
		'imagesy'                 => true,
		'imagedashedline'         => true,
		'imagettfbbox'            => true,
		'imagettftext'            => true,
		'imageftbbox'             => true,
		'imagefttext'             => true,
		'imagepsloadfont'         => true,
		'imagepsfreefont'         => true,
		'imagepsencodefont'       => true,
		'imagepsextendfont'       => true,
		'imagepsslantfont'        => true,
		'imagepstext'             => true,
		'imagepsbbox'             => true,
		'imagetypes'              => true,
		'jpeg2wbmp'               => true,
		'png2wbmp'                => true,
		'image2wbmp'              => true,
		'imagelayereffect'        => true,
		'imagecolormatch'         => true,
		'getimagesize'            => true,
		'image_type_to_mime_type' => true,
		'iptcembed'               => true,
		'iptcparse'               => true,
	),
);
