<?php /* $Id: frame.inc 15342 2006-12-01 21:14:46Z andy_st $ */
  /* Contributed by: floridave */
$frameData = array(

'name' => $gallery->i18n('Bamboo'),

/* Top Left */
'imageTL' => 'TL.gif',
'widthTL' => 28,
'heightTL' => 28,

/* Top */
'imageTTL' => 'TTL.gif',
'widthTTL' => 54,

'imageTT' => 'TT.gif',
'heightTT' => 28,

'imageTTR' => 'TTR.gif',
'widthTTR' => 54,

/* Top Right */
'imageTR' => 'TR.gif',
'widthTR' => 28,
'heightTR' => 28,

/* Left */
'imageLLT' => 'LLT.gif',
'heightLLT' => 54,

'imageLL' => 'LL.gif',
'widthLL' => 28,

'imageLLB' => 'LLB.gif',
'heightLLB' => 54,

/* Right */
'imageRRT' => 'RRT.gif',
'heightRRT' => 54,

'imageRR' => 'RR.gif',
'widthRR' => 28,

'imageRRB' => 'RRB.gif',
'heightRRB' => 54,

/* Bottom Left */
'imageBL' => 'BL.gif',
'widthBL' => 28,
'heightBL' => 28,

/* Bottom */
'imageBBL' => 'BBL.gif',
'widthBBL' => 54,

'imageBB' => 'BB.gif',
'heightBB' => 28,

'imageBBR' => 'BBR.gif',
'widthBBR' => 54,

/* Bottom Right */
'imageBR' => 'BR.gif',
'widthBR' => 28,
'heightBR' => 28

);
?>
