## mysql
# R_RewriteMap_1.0
DROP TABLE DB_TABLE_PREFIXRewriteMap;

DELETE FROM DB_TABLE_PREFIXSchema WHERE DB_COLUMN_PREFIXname='RewriteMap';

## postgres
# R_RewriteMap_1.0
DROP TABLE DB_TABLE_PREFIXRewriteMap;

DELETE FROM DB_TABLE_PREFIXSchema WHERE DB_COLUMN_PREFIXname='RewriteMap';

## oracle
# R_RewriteMap_1.0
DROP TABLE DB_TABLE_PREFIXRewriteMap;

DELETE FROM DB_TABLE_PREFIXSchema WHERE DB_COLUMN_PREFIXname='RewriteMap';

## db2
# R_RewriteMap_1.0
DROP TABLE DB_TABLE_PREFIXRewriteMap;

DELETE FROM DB_TABLE_PREFIXSchema WHERE DB_COLUMN_PREFIXname='RewriteMap';

## mssql
# R_RewriteMap_1.0
DROP TABLE DB_TABLE_PREFIXRewriteMap;

DELETE FROM DB_TABLE_PREFIXSchema WHERE DB_COLUMN_PREFIXname='RewriteMap';

## sqlite
# R_RewriteMap_1.0
DROP TABLE DB_TABLE_PREFIXRewriteMap;

DELETE FROM DB_TABLE_PREFIXSchema WHERE DB_COLUMN_PREFIXname='RewriteMap';

