<?php /* $Id: frame.inc 15342 2006-12-01 21:14:46Z andy_st $ */
  /* Contributed by: carlandtracey.com */
$frameData = array(

'name' => $gallery->i18n('Spiral Notebook (square)'),
'square' => true,

/* Center */
'imageCC' => 'CC.gif',

/* Top Left */
'imageTL' => 'TL.gif',
'widthTL' => 30,
'heightTL' => 14,

/* Top */
'imageTTL' => '',
'widthTTL' => 0,

'imageTT' => 'TT.gif',
'heightTT' => 14,

'imageTTR' => '',
'widthTTR' => 0,

/* Top Right */
'imageTR' => 'TR.gif',
'widthTR' => 15,
'heightTR' => 14,

/* Left */
'imageLLT' => '',
'heightLLT' => 0,

'imageLL' => 'LL.gif',
'widthLL' => 30,

'imageLLB' => '',
'heightLLB' => 0,

/* Right */
'imageRRT' => '',
'heightRRT' => 0,

'imageRR' => 'RR.gif',
'widthRR' => 15,

'imageRRB' => '',
'heightRRB' => 0,

/* Bottom Left */
'imageBL' => 'BL.gif',
'widthBL' => 30,
'heightBL' => 15,

/* Bottom */
'imageBBL' => '',
'widthBBL' => 0,

'imageBB' => 'BB.gif',
'heightBB' => 15,

'imageBBR' => '',
'widthBBR' => 0,

/* Bottom Right */
'imageBR' => 'BR.gif',
'widthBR' => 15,
'heightBR' => 15

);
?>
