<?php /* $Id: frame.inc 15342 2006-12-01 21:14:46Z andy_st $ */
  /* Contributed by: KnightScene */
$frameData = array(

'name' => $gallery->i18n('Photo Corners'),

/* Top Left */
'imageTL' => 'TL.gif',
'widthTL' => 60,
'heightTL' => 60,

/* Top */
'imageTTL' => '',
'widthTTL' => 0,

'imageTT' => 'TT.gif',
'heightTT' => 60,

'imageTTR' => '',
'widthTTR' => 0,

/* Top Right */
'imageTR' => 'TR.gif',
'widthTR' => 60,
'heightTR' => 60,

/* Left */
'imageLLT' => '',
'heightLLT' => 0,

'imageLL' => 'LL.gif',
'widthLL' => 60,

'imageLLB' => '',
'heightLLB' => 0,

/* Right */
'imageRRT' => '',
'heightRRT' => 0,

'imageRR' => 'RR.gif',
'widthRR' => 60,

'imageRRB' => '',
'heightRRB' => 0,

/* Bottom Left */
'imageBL' => 'BL.gif',
'widthBL' => 60,
'heightBL' => 60,

/* Bottom */
'imageBBL' => '',
'widthBBL' => 0,

'imageBB' => 'BB.gif',
'heightBB' => 60,

'imageBBR' => '',
'widthBBR' => 0,

/* Bottom Right */
'imageBR' => 'BR.gif',
'widthBR' => 60,
'heightBR' => 60

);
?>
