<?php /* $Id: frame.inc 15342 2006-12-01 21:14:46Z andy_st $ */
$frameData = array(

'name' => $gallery->i18n('Polaroids'),

/* Top Left */
'imageTL' => 'TL.gif',
'widthTL' => 10,
'heightTL' => 10,

/* Top */
'imageTTL' => '',
'widthTTL' => 0,

'imageTT' => 'TT.gif',
'heightTT' => 10,

'imageTTR' => '',
'widthTTR' => 0,

/* Top Right */
'imageTR' => 'TR.gif',
'widthTR' => 19,
'heightTR' => 10,

/* Left */
'imageLLT' => '',
'heightLLT' => 0,

'imageLL' => 'LL.gif',
'widthLL' => 10,

'imageLLB' => '',
'heightLLB' => 0,

/* Right */
'imageRRT' => '',
'heightRRT' => 0,

'imageRR' => 'RR.gif',
'widthRR' => 19,

'imageRRB' => '',
'heightRRB' => 0,

/* Bottom Left */
'imageBL' => 'BL.gif',
'widthBL' => 10,
'heightBL' => 39,

/* Bottom */
'imageBBL' => '',
'widthBBL' => 0,

'imageBB' => 'BB.gif',
'heightBB' => 39,

'imageBBR' => '',
'widthBBR' => 0,

/* Bottom Right */
'imageBR' => 'BR.gif',
'widthBR' => 19,
'heightBR' => 39

);
?>
