## mysql
# ItemHiddenMap
CREATE TABLE DB_TABLE_PREFIXItemHiddenMap(
 DB_COLUMN_PREFIXitemId int(11) NOT NULL,
 PRIMARY KEY(DB_COLUMN_PREFIXitemId)
) DB_TABLE_TYPE
/*!40100 DEFAULT CHARACTER SET utf8 */;

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('ItemHiddenMap', 1, 0);

## postgres
# ItemHiddenMap
CREATE TABLE DB_TABLE_PREFIXItemHiddenMap(
 DB_COLUMN_PREFIXitemId INTEGER NOT NULL
);

ALTER TABLE DB_TABLE_PREFIXItemHiddenMap ADD PRIMARY KEY (DB_COLUMN_PREFIXitemId);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('ItemHiddenMap', 1, 0);

## oracle
# ItemHiddenMap
CREATE TABLE DB_TABLE_PREFIXItemHiddenMap(
 DB_COLUMN_PREFIXitemId INTEGER NOT NULL
);

ALTER TABLE DB_TABLE_PREFIXItemHiddenMap
 ADD PRIMARY KEY (DB_COLUMN_PREFIXitemId)
;

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('ItemHiddenMap', 1, 0);

## db2
# ItemHiddenMap
CREATE TABLE DB_TABLE_PREFIXItemHiddenMap(
 DB_COLUMN_PREFIXitemId INTEGER NOT NULL
);

ALTER TABLE DB_TABLE_PREFIXItemHiddenMap ADD PRIMARY KEY (DB_COLUMN_PREFIXitemId);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('ItemHiddenMap', 1, 0);

## mssql
# ItemHiddenMap
CREATE TABLE DB_TABLE_PREFIXItemHiddenMap(
 DB_COLUMN_PREFIXitemId INT NOT NULL
);

ALTER TABLE DB_TABLE_PREFIXItemHiddenMap ADD PRIMARY KEY (DB_COLUMN_PREFIXitemId);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('ItemHiddenMap', 1, 0);

## sqlite
# ItemHiddenMap
CREATE TABLE DB_TABLE_PREFIXItemHiddenMap(
 DB_COLUMN_PREFIXitemId INTEGER NOT NULL
);

CREATE UNIQUE INDEX DB_TABLE_PREFIXItemHiddenMap_pkey ON DB_TABLE_PREFIXItemHiddenMap(DB_COLUMN_PREFIXitemId);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('ItemHiddenMap', 1, 0);

