<?php
// Google map control sizes and locations
  // Contributed by: floridave
  // GxMagnifier image placement at bottom
// Center
$map['imageCenter'] = 'Center.png';
$map['widthC']      = '19';
$map['heightC']     = '19';
$map['padTopC']     = '40';
$map['padLeftC']    = '24';

// Center Background
$map['imageCenterBG'] = 'CenterBG.png';
$map['widthCBG']      = '55';
$map['heightCBG']     = '55';
$map['padTopCBG']     = '23';
$map['padLeftCBG']    = '7';

// North
$map['imageNorth'] = 'North.png';
$map['widthN']     = '19';
$map['heightN']    = '17';
$map['padTopN']    = '23';
$map['padLeftN']   = '24';

// South
$map['imageSouth'] = 'South.png';
$map['widthS']     = '19';
$map['heightS']    = '17';
$map['padTopS']    = '59';
$map['padLeftS']   = '24';

// East
$map['imageEast'] = 'East.png';
$map['widthE']    = '17';
$map['heightE']   = '19';
$map['padTopE']   = '40';
$map['padLeftE']  = '43';

// West
$map['imageWest'] = 'West.png';
$map['widthW']    = '17';
$map['heightW']   = '19';
$map['padTopW']   = '40';
$map['padLeftW']  = '7';

// ZoomIn
$map['imageIn']   = 'ZoomIn.png';
$map['widthIn']   = '19';
$map['heightIn']  = '16';
$map['padTopIn']  = '80';
$map['padLeftIn'] = '25';

// ZoomOut
$map['imageOut']   = 'ZoomOut.png';
$map['widthOut']   = '19';
$map['heightOut']  = '16';
$map['padTopOut']  = '228';
$map['padLeftOut'] = '25';

// SlideNotch
$map['imageSlideNotch']  = 'SlideNotch.png';
$map['widthSlideNotch']  = '19';
$map['heightSlideNotch'] = '7';

// SlideSel
$map['imageSlideSel']  = 'SlideSel.png';
$map['widthSlideSel']  = '19';
$map['heightSlideSel'] = '7';

// zoomControl position
$map['padTopzoomControl']  = '95';
$map['padLeftzoomControl'] = '25';

// mapTypes
$map['linkTypeColor'] = 'FFFFFF';
$map['imageTypeBG']   = 'TypeBG.png';

// mapTypeMap
$map['widthTypeMap']   = '65';
$map['padTopTypeMap']  = '260';
$map['padLeftTypeMap'] = '0';

// mapTypeSat
$map['widthTypeSat']   = '65';
$map['padTopTypeSat']  = '280';
$map['padLeftTypeSat'] = '0';

// mapTypeHyb
$map['widthTypeHyb']   = '65';
$map['padTopTypeHyb']  = '300';
$map['padLeftTypeHyb'] = '0';

// GxMagnifier location
$map['GxPosY'] = '10';
$map['GxPosX'] = '4';
