## mysql
# mapv3Map
CREATE TABLE DB_TABLE_PREFIXmapv3Map(
 DB_COLUMN_PREFIXitemId varchar(11) NOT NULL,
 DB_COLUMN_PREFIXfield varchar(128) NOT NULL,
 DB_COLUMN_PREFIXvalue varchar(255),
 DB_COLUMN_PREFIXsetId int(11),
 DB_COLUMN_PREFIXsetType int(11),
 INDEX DB_TABLE_PREFIXmapv3Map_75985(DB_COLUMN_PREFIXitemId)
) TYPE=DB_TABLE_TYPE ;

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('mapv3Map', 1, 1);

## postgres
# mapv3Map
CREATE TABLE DB_TABLE_PREFIXmapv3Map(
 DB_COLUMN_PREFIXitemId varchar(11) NOT NULL,
 DB_COLUMN_PREFIXfield VARCHAR(128) NOT NULL,
 DB_COLUMN_PREFIXvalue VARCHAR(255),
 DB_COLUMN_PREFIXsetId INTEGER,
 DB_COLUMN_PREFIXsetType INTEGER
);

CREATE INDEX DB_TABLE_PREFIXmapv3Map_75985 ON DB_TABLE_PREFIXmapv3Map(DB_COLUMN_PREFIXitemId);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('mapv3Map', 1, 1);

## oracle
# mapv3Map
CREATE TABLE DB_TABLE_PREFIXmapv3Map(
 DB_COLUMN_PREFIXitemId varchar(11) NOT NULL,
 DB_COLUMN_PREFIXfield VARCHAR2(128) NOT NULL,
 DB_COLUMN_PREFIXvalue VARCHAR2(255),
 DB_COLUMN_PREFIXsetId INTEGER,
 DB_COLUMN_PREFIXsetType INTEGER
);

CREATE INDEX DB_TABLE_PREFIXmapv3Map_75985
   ON DB_TABLE_PREFIXmapv3Map(DB_COLUMN_PREFIXitemId);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('mapv3Map', 1, 1);

## db2
# mapv3Map
CREATE TABLE DB_TABLE_PREFIXmapv3Map(
 DB_COLUMN_PREFIXitemId varchar(11) NOT NULL,
 DB_COLUMN_PREFIXfield VARCHAR(128) NOT NULL,
 DB_COLUMN_PREFIXvalue VARCHAR(255),
 DB_COLUMN_PREFIXsetId INTEGER,
 DB_COLUMN_PREFIXsetType INTEGER
);

CREATE INDEX DB_TABLE_PREFIXCusto65_75985
   ON DB_TABLE_PREFIXmapv3Map(DB_COLUMN_PREFIXitemId);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('mapv3Map', 1, 1);

