<?php /* $Id: frame.inc 15342 2006-12-01 21:14:46Z andy_st $ */
  /* Contributed by: demonhood */
$frameData = array(

'name' => $gallery->i18n('Postage'),

/* Top Left */
'imageTL' => 'TL5.gif',
'widthTL' => 10,
'heightTL' => 10,

/* Top */
'imageTTL' => '',
'widthTTL' => 0,

'imageTT' => 'TT5.gif',
'heightTT' => 10,

'imageTTR' => '',
'widthTTR' => 0,

/* Top Right */
'imageTR' => 'TR5.gif',
'widthTR' => 10,
'heightTR' => 10,

/* Left */
'imageLLT' => '',
'heightLLT' => 0,

'imageLL' => 'LL5.gif',
'widthLL' => 10,

'imageLLB' => '',
'heightLLB' => 0,

/* Right */
'imageRRT' => '',
'heightRRT' => 0,

'imageRR' => 'RR5.gif',
'widthRR' => 10,

'imageRRB' => '',
'heightRRB' => 0,

/* Bottom Left */
'imageBL' => 'BL5.gif',
'heightBL' => 10,
'widthBL' => 10,

/* Bottom */
'imageBBL' => '',
'widthBBL' => 0,

'imageBB' => 'BB5.gif',
'heightBB' => 10,

'imageBBR' => '',
'widthBBR' => 0,

/* Bottom Right */
'imageBR' => 'BR5.gif',
'widthBR' => 10,
'heightBR' => 10,

);
?>
