<?php /* $Id: frame.inc 15342 2006-12-01 21:14:46Z andy_st $ */
  /* Contributed by: KnightScene */
$frameData = array(

'name' => $gallery->i18n('Film Edges'),

/* Top Left */
'imageTL' => 'TL.gif',
'widthTL' => 6,
'heightTL' => 18,

/* Top */
'imageTTL' => 'TTL.gif',
'widthTTL' => 88,

'imageTT' => 'TT.gif',
'heightTT' => 18,

'imageTTR' => '',
'widthTTR' => 0,

/* Top Right */
'imageTR' => 'TR.gif',
'widthTR' => 8,
'heightTR' => 18,

/* Left */
'imageLLT' => '',
'heightLLT' => 0,

'imageLL' => 'LL.gif',
'widthLL' => 6,

'imageLLB' => '',
'heightLLB' => 0,

/* Right */
'imageRRT' => '',
'heightRRT' => 0,

'imageRR' => 'RR.gif',
'widthRR' => 8,

'imageRRB' => '',
'heightRRB' => 0,

/* Bottom Left */
'imageBL' => 'BL.gif',
'widthBL' => 6,
'heightBL' => 18,

/* Bottom */
'imageBBL' => 'BBL.gif',
'widthBBL' => 88,

'imageBB' => 'BB.gif',
'heightBB' => 18,

'imageBBR' => '',
'widthBBR' => 0,

/* Bottom Right */
'imageBR' => 'BR.gif',
'widthBR' => 8,
'heightBR' => 18

);
?>
