## mysql
# RssMap
CREATE TABLE DB_TABLE_PREFIXRssMap(
 DB_COLUMN_PREFIXfeedName varchar(128) NOT NULL,
 DB_COLUMN_PREFIXitemId int(11) NOT NULL,
 DB_COLUMN_PREFIXownerId int(11) NOT NULL,
 DB_COLUMN_PREFIXparams text NOT NULL,
 PRIMARY KEY(DB_COLUMN_PREFIXfeedName),
 INDEX DB_TABLE_PREFIXRssMap_75985(DB_COLUMN_PREFIXitemId),
 INDEX DB_TABLE_PREFIXRssMap_21573(DB_COLUMN_PREFIXownerId)
) DB_TABLE_TYPE
/*!40100 DEFAULT CHARACTER SET utf8 */;

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('RssMap', 1, 0);

## postgres
# RssMap
CREATE TABLE DB_TABLE_PREFIXRssMap(
 DB_COLUMN_PREFIXfeedName VARCHAR(128) NOT NULL,
 DB_COLUMN_PREFIXitemId INTEGER NOT NULL,
 DB_COLUMN_PREFIXownerId INTEGER NOT NULL,
 DB_COLUMN_PREFIXparams text NOT NULL
);

ALTER TABLE DB_TABLE_PREFIXRssMap ADD PRIMARY KEY (DB_COLUMN_PREFIXfeedName);

CREATE INDEX DB_TABLE_PREFIXRssMap_75985 ON DB_TABLE_PREFIXRssMap(DB_COLUMN_PREFIXitemId);

CREATE INDEX DB_TABLE_PREFIXRssMap_21573 ON DB_TABLE_PREFIXRssMap(DB_COLUMN_PREFIXownerId);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('RssMap', 1, 0);

## oracle
# RssMap
CREATE TABLE DB_TABLE_PREFIXRssMap(
 DB_COLUMN_PREFIXfeedName VARCHAR2(128) NOT NULL,
 DB_COLUMN_PREFIXitemId INTEGER NOT NULL,
 DB_COLUMN_PREFIXownerId INTEGER NOT NULL,
 DB_COLUMN_PREFIXparams VARCHAR2(4000) NOT NULL
);

CREATE INDEX DB_TABLE_PREFIXRssMap_75985
   ON DB_TABLE_PREFIXRssMap(DB_COLUMN_PREFIXitemId);

CREATE INDEX DB_TABLE_PREFIXRssMap_21573
   ON DB_TABLE_PREFIXRssMap(DB_COLUMN_PREFIXownerId);

ALTER TABLE DB_TABLE_PREFIXRssMap
 ADD PRIMARY KEY (DB_COLUMN_PREFIXfeedName)
;

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('RssMap', 1, 0);

## db2
# RssMap
CREATE TABLE DB_TABLE_PREFIXRssMap(
 DB_COLUMN_PREFIXfeedName VARCHAR(128) NOT NULL,
 DB_COLUMN_PREFIXitemId INTEGER NOT NULL,
 DB_COLUMN_PREFIXownerId INTEGER NOT NULL,
 DB_COLUMN_PREFIXparams VARCHAR(10000) NOT NULL
);

ALTER TABLE DB_TABLE_PREFIXRssMap ADD PRIMARY KEY (DB_COLUMN_PREFIXfeedName);

CREATE INDEX DB_TABLE_PREFIXRssMa42_75985
   ON DB_TABLE_PREFIXRssMap(DB_COLUMN_PREFIXitemId);

CREATE INDEX DB_TABLE_PREFIXRssMa42_21573
   ON DB_TABLE_PREFIXRssMap(DB_COLUMN_PREFIXownerId);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('RssMap', 1, 0);

## mssql
# RssMap
CREATE TABLE DB_TABLE_PREFIXRssMap(
 DB_COLUMN_PREFIXfeedName NVARCHAR(128) NOT NULL,
 DB_COLUMN_PREFIXitemId INT NOT NULL,
 DB_COLUMN_PREFIXownerId INT NOT NULL,
 DB_COLUMN_PREFIXparams NVARCHAR(MAX) NOT NULL
);

ALTER TABLE DB_TABLE_PREFIXRssMap ADD PRIMARY KEY (DB_COLUMN_PREFIXfeedName);

CREATE INDEX DB_TABLE_PREFIXRssMap_75985 ON DB_TABLE_PREFIXRssMap(DB_COLUMN_PREFIXitemId);

CREATE INDEX DB_TABLE_PREFIXRssMap_21573 ON DB_TABLE_PREFIXRssMap(DB_COLUMN_PREFIXownerId);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('RssMap', 1, 0);

## sqlite
# RssMap
CREATE TABLE DB_TABLE_PREFIXRssMap(
 DB_COLUMN_PREFIXfeedName TEXT NOT NULL,
 DB_COLUMN_PREFIXitemId INTEGER NOT NULL,
 DB_COLUMN_PREFIXownerId INTEGER NOT NULL,
 DB_COLUMN_PREFIXparams TEXT NOT NULL
);

CREATE UNIQUE INDEX DB_TABLE_PREFIXRssMap_pkey ON DB_TABLE_PREFIXRssMap(DB_COLUMN_PREFIXfeedName);

CREATE INDEX DB_TABLE_PREFIXRssMap_75985 ON DB_TABLE_PREFIXRssMap(DB_COLUMN_PREFIXitemId);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('RssMap', 1, 0);

