<?php /* $Id: frame.inc 15342 2006-12-01 21:14:46Z andy_st $ */
  /* Contributed by: floridave */
$frameData = array(

'name' => $gallery->i18n('Branded Wood'),

/* Top Left */
'imageTL' => 'TL.jpg',
'widthTL' => 25,
'heightTL' => 25,

/* Top */
'imageTTL' => 'TTL.jpg',
'widthTTL' => 35,

'imageTT' => 'TT.jpg',
'heightTT' => 25,

'imageTTR' => 'TTR.jpg',
'widthTTR' => 35,

/* Top Right */
'imageTR' => 'TR.jpg',
'widthTR' => 25,
'heightTR' => 25,

/* Left */
'imageLLT' => 'LLT.jpg',
'heightLLT' => 35,

'imageLL' => 'LL.jpg',
'widthLL' => 25,

'imageLLB' => 'LLB.jpg',
'heightLLB' => 35,

/* Right */
'imageRRT' => 'RRT.jpg',
'heightRRT' => 35,

'imageRR' => 'RR.jpg',
'widthRR' => 25,

'imageRRB' => 'RRB.jpg',
'heightRRB' => 35,

/* Bottom Left */
'imageBL' => 'BL.jpg',
'widthBL' => 25,
'heightBL' => 25,

/* Bottom */
'imageBBL' => 'BBL.jpg',
'widthBBL' => 35,

'imageBB' => 'BB.jpg',
'heightBB' => 25,

'imageBBR' => 'BBR.jpg',
'widthBBR' => 35,

/* Bottom Right */
'imageBR' => 'BR.jpg',
'widthBR' => 25,
'heightBR' => 25

);
?>
