<?php /* $Id: frame.inc 15342 2006-12-01 21:14:46Z andy_st $ */
  /* Contributed by: xlerb */
$frameData = array(

'name' => $gallery->i18n('Slide (square)'),
'square' => true,

/* Center, no width/height setting neccessary */
/* Try setting this to 'CC.png' to see the centering, then make your own appealing img. */
'imageCC' => 'CC.gif',

/* Top Left */
'imageTL' => 'TL.gif',
'widthTL' => 11,
'heightTL' => 11,

/* Top */
'imageTTL' => '',
'widthTTL' => 0,

'imageTT' => 'TT.gif',
'heightTT' => 11,

'imageTTR' => '',
'widthTTR' => 0,

/* Top Right */
'imageTR' => 'TR.gif',
'widthTR' => 11,
'heightTR' => 11,

/* Left */
'imageLLT' => '',
'heightLLT' => 0,

'imageLL' => 'LL.gif',
'widthLL' => 11,

'imageLLB' => '',
'heightLLB' => 0,

/* Right */
'imageRRT' => '',
'heightRRT' => 0,

'imageRR' => 'RR.gif',
'widthRR' => 11,

'imageRRB' => '',
'heightRRB' => 0,

/* Bottom Left */
'imageBL' => 'BL.gif',
'widthBL' => 11,
'heightBL' => 11,

/* Bottom */
'imageBBL' => '',
'widthBBL' => 0,

'imageBB' => 'BB.gif',
'heightBB' => 11,

'imageBBR' => '',
'widthBBR' => 0,

/* Bottom Right */
'imageBR' => 'BR.gif',
'widthBR' => 11,
'heightBR' => 11

);
?>
