<?php /* $Id: frame.inc 15342 2006-12-01 21:14:46Z andy_st $ */
$frameData = array(

'name' => $gallery->i18n('Shadow'),

/* Top Left */
'imageTL' => '',
'widthTL' => 0,
'heightTL' => 0,

/* Top */
'imageTTL' => '',
'widthTTL' => 0,

'imageTT' => '',
'heightTT' => 0,

'imageTTR' => '',
'widthTTR' => 0,

/* Top Right */
'imageTR' => '',
'widthTR' => 0,
'heightTR' => 0,

/* Left */
'imageLLT' => '',
'heightLLT' => 0,

'imageLL' => '',
'widthLL' => 0,

'imageLLB' => '',
'heightLLB' => 0,

/* Right */
'imageRRT' => 'RRT.png',
'heightRRT' => 10,

'imageRR' => 'RR.png',
'widthRR' => 7,

'imageRRB' => '',
'heightRRB' => 0,

/* Bottom Left */
'imageBL' => '',
'widthBL' => 0,
'heightBL' => 0,

/* Bottom */
'imageBBL' => 'BBL.png',
'widthBBL' => 9,

'imageBB' => 'BB.png',
'heightBB' => 7,

'imageBBR' => '',
'widthBBR' => 0,

/* Bottom Right */
'imageBR' => 'BR.png',
'widthBR' => 7,
'heightBR' => 7

);
?>
