<?php
// Google map control sizes and locations
  // Contributed by: floridave
  // GxMagnifier image placement at bottom
// Center
$map['imageCenter'] = 'center.png';
$map['widthC']      = '19';
$map['heightC']     = '19';
$map['padTopC']     = '23';
$map['padLeftC']    = '22';

// Center Background
$map['imageCenterBG'] = 'blank.gif';
$map['widthCBG']      = '1';
$map['heightCBG']     = '1';
$map['padTopCBG']     = '10';
$map['padLeftCBG']    = '9';

// North
$map['imageNorth'] = 'north.png';
$map['widthN']     = '18';
$map['heightN']    = '14';
$map['padTopN']    = '5';
$map['padLeftN']   = '23';

// South
$map['imageSouth'] = 'south.png';
$map['widthS']     = '18';
$map['heightS']    = '14';
$map['padTopS']    = '46';
$map['padLeftS']   = '23';

// East
$map['imageEast'] = 'east.png';
$map['widthE']    = '14';
$map['heightE']   = '18';
$map['padTopE']   = '24';
$map['padLeftE']  = '45';

// West
$map['imageWest'] = 'west.png';
$map['widthW']    = '14';
$map['heightW']   = '18';
$map['padTopW']   = '24';
$map['padLeftW']  = '5';

// ZoomIn
$map['imageIn']   = 'zoom-in.png';
$map['widthIn']   = '19';
$map['heightIn']  = '16';
$map['padTopIn']  = '65';
$map['padLeftIn'] = '15';

// ZoomOut
$map['imageOut']   = 'zoom-out.png';
$map['widthOut']   = '19';
$map['heightOut']  = '16';
$map['padTopOut']  = '230';
$map['padLeftOut'] = '15';

// SlideNotch
$map['imageSlideNotch']  = 'SlideNotch.png';
$map['widthSlideNotch']  = '19';
$map['heightSlideNotch'] = '7';

// SlideSel
$map['imageSlideSel']  = 'SlideSel.png';
$map['widthSlideSel']  = '19';
$map['heightSlideSel'] = '7';

// zoomControl position
$map['padTopzoomControl']  = '75';
$map['padLeftzoomControl'] = '15';

// mapTypes
$map['linkTypeColor'] = '000000';
$map['imageTypeBG']   = 'TypeBG.png';

// mapTypeMap
$map['widthTypeMap']   = '60';
$map['padTopTypeMap']  = '0';
$map['padLeftTypeMap'] = '290';

// mapTypeSat
$map['widthTypeSat']   = '100';
$map['padTopTypeSat']  = '0';
$map['padLeftTypeSat'] = '340';

// mapTypeHyb
$map['widthTypeHyb']   = '75';
$map['padTopTypeHyb']  = '0';
$map['padLeftTypeHyb'] = '430';

// GxMagnifier location
$map['GxPosY'] = '4';
$map['GxPosX'] = '4';
